// <auto-generated>
// This code is generated by the Sakura framework source generator.
// Generator name : Sakura.Framework.SourceGenerators.Generators.MathStructGenerator
// Type wrapper for System.Numerics.Matrix3x2 for Matrix3x2
// Last updated : 2025-09-08 21:01:34 UTC
// </auto-generated>
namespace Sakura.Framework.Maths;

public readonly partial struct Matrix3x2 : System.IEquatable<Matrix3x2>
{
    /// <summary>Creates a 3x2 matrix from the specified components.</summary>
    /// <param name="m11">The value to assign to the first element in the first row.</param>
    /// <param name="m12">The value to assign to the second element in the first row.</param>
    /// <param name="m21">The value to assign to the first element in the second row.</param>
    /// <param name="m22">The value to assign to the second element in the second row.</param>
    /// <param name="m31">The value to assign to the first element in the third row.</param>
    /// <param name="m32">The value to assign to the second element in the third row.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Matrix3x2(float m11, float m12, float m21, float m22, float m31, float m32)
    {
        this.Value = new System.Numerics.Matrix3x2(m11, m12, m21, m22, m31, m32);
    }

    /// <summary>Adds each element in one matrix with its corresponding element in a second matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix that contains the summed values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 operator +(Matrix3x2 value1, Matrix3x2 value2) => value1 + value2;

    /// <summary>Returns a value that indicates whether the specified matrices are equal.</summary>
    /// <param name="value1">The first matrix to compare.</param>
    /// <param name="value2">The second matrix to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="value1" /> and <paramref name="value2" /> are equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Matrix3x2 value1, Matrix3x2 value2) => value1 == value2;

    /// <summary>Returns a value that indicates whether the specified matrices are not equal.</summary>
    /// <param name="value1">The first matrix to compare.</param>
    /// <param name="value2">The second matrix to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="value1" /> and <paramref name="value2" /> are not equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Matrix3x2 value1, Matrix3x2 value2) => value1 != value2;

    /// <summary>Returns the matrix that results from multiplying two matrices together.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The product matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 operator *(Matrix3x2 value1, Matrix3x2 value2) => value1 * value2;

    /// <summary>Returns the matrix that results from scaling all the elements of a specified matrix by a scalar factor.</summary>
    /// <param name="value1">The matrix to scale.</param>
    /// <param name="value2">The scaling value to use.</param>
    /// <returns>The scaled matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 operator *(Matrix3x2 value1, float value2) => value1 * value2;

    /// <summary>Subtracts each element in a second matrix from its corresponding element in a first matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix containing the values that result from subtracting each element in <paramref name="value2" /> from its corresponding element in <paramref name="value1" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 operator -(Matrix3x2 value1, Matrix3x2 value2) => value1 - value2;

    /// <summary>Negates the specified matrix by multiplying all its values by -1.</summary>
    /// <param name="value">The matrix to negate.</param>
    /// <returns>The negated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 operator -(Matrix3x2 value) => -value;

    /// <summary>Adds each element in one matrix with its corresponding element in a second matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix that contains the summed values of <paramref name="value1" /> and <paramref name="value2" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Add(Matrix3x2 value1, Matrix3x2 value2) => System.Numerics.Matrix3x2.Add(value1, value2);

    /// <summary>Creates a rotation matrix using the given rotation in radians.</summary>
    /// <param name="radians">The amount of rotation, in radians.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateRotation(float radians) => System.Numerics.Matrix3x2.CreateRotation(radians);

    /// <summary>Creates a rotation matrix using the specified rotation in radians and a center point.</summary>
    /// <param name="radians">The amount of rotation, in radians.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateRotation(float radians, Vector2 centerPoint) => System.Numerics.Matrix3x2.CreateRotation(radians, centerPoint);

    /// <summary>Creates a scaling matrix from the specified vector scale.</summary>
    /// <param name="scales">The scale to use.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(Vector2 scales) => System.Numerics.Matrix3x2.CreateScale(scales);

    /// <summary>Creates a scaling matrix from the specified vector scale with an offset from the specified center point.</summary>
    /// <param name="scales">The scale to use.</param>
    /// <param name="centerPoint">The center offset.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(Vector2 scales, Vector2 centerPoint) => System.Numerics.Matrix3x2.CreateScale(scales, centerPoint);

    /// <summary>Creates a scaling matrix that scales uniformly with the given scale.</summary>
    /// <param name="scale">The uniform scale to use.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(float scale) => System.Numerics.Matrix3x2.CreateScale(scale);

    /// <summary>Creates a scaling matrix that scales uniformly with the specified scale with an offset from the specified center.</summary>
    /// <param name="scale">The uniform scale to use.</param>
    /// <param name="centerPoint">The center offset.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(float scale, Vector2 centerPoint) => System.Numerics.Matrix3x2.CreateScale(scale, centerPoint);

    /// <summary>Creates a scaling matrix from the specified X and Y components.</summary>
    /// <param name="xScale">The value to scale by on the X axis.</param>
    /// <param name="yScale">The value to scale by on the Y axis.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(float xScale, float yScale) => System.Numerics.Matrix3x2.CreateScale(xScale, yScale);

    /// <summary>Creates a scaling matrix that is offset by a given center point.</summary>
    /// <param name="xScale">The value to scale by on the X axis.</param>
    /// <param name="yScale">The value to scale by on the Y axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateScale(float xScale, float yScale, Vector2 centerPoint) => System.Numerics.Matrix3x2.CreateScale(xScale, yScale, centerPoint);

    /// <summary>Creates a skew matrix from the specified angles in radians.</summary>
    /// <param name="radiansX">The X angle, in radians.</param>
    /// <param name="radiansY">The Y angle, in radians.</param>
    /// <returns>The skew matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateSkew(float radiansX, float radiansY) => System.Numerics.Matrix3x2.CreateSkew(radiansX, radiansY);

    /// <summary>Creates a skew matrix from the specified angles in radians and a center point.</summary>
    /// <param name="radiansX">The X angle, in radians.</param>
    /// <param name="radiansY">The Y angle, in radians.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The skew matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateSkew(float radiansX, float radiansY, Vector2 centerPoint) => System.Numerics.Matrix3x2.CreateSkew(radiansX, radiansY, centerPoint);

    /// <summary>Creates a translation matrix from the specified 2-dimensional vector.</summary>
    /// <param name="position">The translation position.</param>
    /// <returns>The translation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateTranslation(Vector2 position) => System.Numerics.Matrix3x2.CreateTranslation(position);

    /// <summary>Creates a translation matrix from the specified X and Y components.</summary>
    /// <param name="xPosition">The X position.</param>
    /// <param name="yPosition">The Y position.</param>
    /// <returns>The translation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 CreateTranslation(float xPosition, float yPosition) => System.Numerics.Matrix3x2.CreateTranslation(xPosition, yPosition);

    /// <summary>Inverts the specified matrix. The return value indicates whether the operation succeeded.</summary>
    /// <param name="matrix">The matrix to invert.</param>
    /// <param name="result">When this method returns, contains the inverted matrix if the operation succeeded.</param>
    /// <returns><see langword="true" /> if <paramref name="matrix" /> was converted successfully; otherwise,  <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool Invert(Matrix3x2 matrix, out Matrix3x2 result)
    {
        System.Numerics.Matrix3x2 resultUnderlying;
        var returnValue = System.Numerics.Matrix3x2.Invert(matrix, out resultUnderlying);
        result = resultUnderlying;
        return returnValue;
    }

    /// <summary>Performs a linear interpolation from one matrix to a second matrix based on a value that specifies the weighting of the second matrix.</summary>
    /// <param name="matrix1">The first matrix.</param>
    /// <param name="matrix2">The second matrix.</param>
    /// <param name="amount">The relative weighting of <paramref name="matrix2" />.</param>
    /// <returns>The interpolated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Lerp(Matrix3x2 matrix1, Matrix3x2 matrix2, float amount) => System.Numerics.Matrix3x2.Lerp(matrix1, matrix2, amount);

    /// <summary>Returns the matrix that results from multiplying two matrices together.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The product matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Multiply(Matrix3x2 value1, Matrix3x2 value2) => System.Numerics.Matrix3x2.Multiply(value1, value2);

    /// <summary>Returns the matrix that results from scaling all the elements of a specified matrix by a scalar factor.</summary>
    /// <param name="value1">The matrix to scale.</param>
    /// <param name="value2">The scaling value to use.</param>
    /// <returns>The scaled matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Multiply(Matrix3x2 value1, float value2) => System.Numerics.Matrix3x2.Multiply(value1, value2);

    /// <summary>Negates the specified matrix by multiplying all its values by -1.</summary>
    /// <param name="value">The matrix to negate.</param>
    /// <returns>The negated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Negate(Matrix3x2 value) => System.Numerics.Matrix3x2.Negate(value);

    /// <summary>Subtracts each element in a second matrix from its corresponding element in a first matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix containing the values that result from subtracting each element in <paramref name="value2" /> from its corresponding element in <paramref name="value1" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix3x2 Subtract(Matrix3x2 value1, Matrix3x2 value2) => System.Numerics.Matrix3x2.Subtract(value1, value2);

    /// <summary>Calculates the determinant for this matrix.</summary>
    /// <returns>The determinant.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float GetDeterminant() => this.Value.GetDeterminant();

    /// <summary>Returns a string that represents this matrix.</summary>
    /// <returns>The string representation of this matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override string ToString() => this.Value.ToString();

    /// <summary>Indicates whether the current object is equal to another object of the same type.</summary>
    /// <param name="other">An object to compare with this object.</param>
    /// <returns><c>true</c> if the current object is equal to the <paramref name="other" /> parameter; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Matrix3x2 other) => this.Value.Equals(other.Value);

    /// <summary>Indicates whether this instance and a specified object are equal.</summary>
    /// <param name="obj">The object to compare with the current instance.</param>
    /// <returns><c>true</c> if <paramref name="obj" /> and this instance are the same type and represent the same value; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object obj) => obj is Matrix3x2 other && Equals(other);

    /// <summary>Returns the hash code for this instance.</summary>
    /// <returns>A 32-bit signed integer that is the hash code for this instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode() => this.Value.GetHashCode();
}
