// <auto-generated>
// This code is generated by the Sakura framework source generator.
// Generator name : Sakura.Framework.SourceGenerators.Generators.MathStructGenerator
// Type wrapper for System.Numerics.Matrix4x4 for Matrix4x4
// Last updated : 2026-06-01 06:58:53 UTC
// </auto-generated>
namespace Sakura.Framework.Maths;

public partial struct Matrix4x4 : System.IEquatable<Matrix4x4>
{
    /// <summary>Creates a <see cref="T:System.Numerics.Matrix4x4" /> object from a specified <see cref="T:System.Numerics.Matrix3x2" /> object.</summary>
    /// <param name="value">A 3x2 matrix.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Matrix4x4(Matrix3x2 value)
    {
        this.Value = new System.Numerics.Matrix4x4(value);
    }

    /// <summary>Creates a 4x4 matrix from the specified components.</summary>
    /// <param name="m11">The value to assign to the first element in the first row.</param>
    /// <param name="m12">The value to assign to the second element in the first row.</param>
    /// <param name="m13">The value to assign to the third element in the first row.</param>
    /// <param name="m14">The value to assign to the fourth element in the first row.</param>
    /// <param name="m21">The value to assign to the first element in the second row.</param>
    /// <param name="m22">The value to assign to the second element in the second row.</param>
    /// <param name="m23">The value to assign to the third element in the second row.</param>
    /// <param name="m24">The value to assign to the fourth element in the second row.</param>
    /// <param name="m31">The value to assign to the first element in the third row.</param>
    /// <param name="m32">The value to assign to the second element in the third row.</param>
    /// <param name="m33">The value to assign to the third element in the third row.</param>
    /// <param name="m34">The value to assign to the fourth element in the third row.</param>
    /// <param name="m41">The value to assign to the first element in the fourth row.</param>
    /// <param name="m42">The value to assign to the second element in the fourth row.</param>
    /// <param name="m43">The value to assign to the third element in the fourth row.</param>
    /// <param name="m44">The value to assign to the fourth element in the fourth row.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Matrix4x4(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44)
    {
        this.Value = new System.Numerics.Matrix4x4(m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44);
    }

    /// <summary>Adds each element in one matrix with its corresponding element in a second matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix that contains the summed values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 operator +(Matrix4x4 value1, Matrix4x4 value2) => value1.Value + value2.Value;

    /// <summary>Returns a value that indicates whether the specified matrices are equal.</summary>
    /// <param name="value1">The first matrix to compare.</param>
    /// <param name="value2">The second matrix to care.</param>
    /// <returns><see langword="true" /> if <paramref name="value1" /> and <paramref name="value2" /> are equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Matrix4x4 value1, Matrix4x4 value2) => value1.Value == value2.Value;

    /// <summary>Returns a value that indicates whether the specified matrices are not equal.</summary>
    /// <param name="value1">The first matrix to compare.</param>
    /// <param name="value2">The second matrix to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="value1" /> and <paramref name="value2" /> are not equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Matrix4x4 value1, Matrix4x4 value2) => value1.Value != value2.Value;

    /// <summary>Returns the matrix that results from multiplying two matrices together.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The product matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 operator *(Matrix4x4 value1, Matrix4x4 value2) => value1.Value * value2.Value;

    /// <summary>Returns the matrix that results from scaling all the elements of a specified matrix by a scalar factor.</summary>
    /// <param name="value1">The matrix to scale.</param>
    /// <param name="value2">The scaling value to use.</param>
    /// <returns>The scaled matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 operator *(Matrix4x4 value1, float value2) => value1.Value * value2;

    /// <summary>Subtracts each element in a second matrix from its corresponding element in a first matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix containing the values that result from subtracting each element in <paramref name="value2" /> from its corresponding element in <paramref name="value1" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 operator -(Matrix4x4 value1, Matrix4x4 value2) => value1.Value - value2.Value;

    /// <summary>Negates the specified matrix by multiplying all its values by -1.</summary>
    /// <param name="value">The matrix to negate.</param>
    /// <returns>The negated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 operator -(Matrix4x4 value) => -value.Value;

    /// <summary>Adds each element in one matrix with its corresponding element in a second matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix that contains the summed values of <paramref name="value1" /> and <paramref name="value2" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Add(Matrix4x4 value1, Matrix4x4 value2) => System.Numerics.Matrix4x4.Add(value1, value2);

    /// <summary>Creates a <see cref="T:System.Numerics.Matrix4x4" /> whose 16 elements are set to the specified value.</summary>
    /// <param name="value">The value to assign to all 16 elements.</param>
    /// <returns>A <see cref="T:System.Numerics.Matrix4x4" /> whose 16 elements are set to <paramref name="value" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Create(float value) => System.Numerics.Matrix4x4.Create(value);

    /// <summary>Creates a <see cref="T:System.Numerics.Matrix4x4" /> from the specified <see cref="T:System.Numerics.Matrix3x2" />.</summary>
    /// <param name="value">The <see cref="T:System.Numerics.Matrix3x2" /> to assign to the first two elements of <see cref="P:System.Numerics.Matrix4x4.X" />, <see cref="P:System.Numerics.Matrix4x4.Y" />, and <see cref="P:System.Numerics.Matrix4x4.W" />.</param>
    /// <returns>A <see cref="T:System.Numerics.Matrix4x4" /> that was initialized using the elements from <paramref name="value" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Create(Matrix3x2 value) => System.Numerics.Matrix4x4.Create(value);

    /// <summary>Creates a <see cref="T:System.Numerics.Matrix4x4" /> whose four rows are set to the specified value.</summary>
    /// <param name="value">The value to assign to all four rows.</param>
    /// <returns>A <see cref="T:System.Numerics.Matrix4x4" /> whose four rows are set to <paramref name="value" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Create(Vector4 value) => System.Numerics.Matrix4x4.Create(value);

    /// <summary>Creates a <see cref="T:System.Numerics.Matrix4x4" /> from the specified rows.</summary>
    /// <param name="x">The value to assign to <see cref="P:System.Numerics.Matrix4x4.X" />.</param>
    /// <param name="y">The value to assign to <see cref="P:System.Numerics.Matrix4x4.Y" />.</param>
    /// <param name="z">The value to assign to <see cref="P:System.Numerics.Matrix4x4.Z" />.</param>
    /// <param name="w">The value to assign to <see cref="P:System.Numerics.Matrix4x4.W" />.</param>
    /// <returns>A <see cref="T:System.Numerics.Matrix4x4" /> whose rows are set to the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Create(Vector4 x, Vector4 y, Vector4 z, Vector4 w) => System.Numerics.Matrix4x4.Create(x, y, z, w);

    /// <summary>Creates a <see cref="T:System.Numerics.Matrix3x2" /> from the specified elements.</summary>
    /// <param name="m11">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M11" />.</param>
    /// <param name="m12">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M12" />.</param>
    /// <param name="m13">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M13" />.</param>
    /// <param name="m14">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M14" />.</param>
    /// <param name="m21">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M21" />.</param>
    /// <param name="m22">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M22" />.</param>
    /// <param name="m23">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M23" />.</param>
    /// <param name="m24">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M24" />.</param>
    /// <param name="m31">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M31" />.</param>
    /// <param name="m32">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M32" />.</param>
    /// <param name="m33">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M33" />.</param>
    /// <param name="m34">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M34" />.</param>
    /// <param name="m41">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M41" />.</param>
    /// <param name="m42">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M42" />.</param>
    /// <param name="m43">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M43" />.</param>
    /// <param name="m44">The value to assign to <see cref="F:System.Numerics.Matrix4x4.M44" />.</param>
    /// <returns>A <see cref="T:System.Numerics.Matrix4x4" /> whose elements are set to the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Create(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44) => System.Numerics.Matrix4x4.Create(m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44);

    /// <summary>Creates a spherical billboard that rotates around a specified object position.</summary>
    /// <param name="objectPosition">The position of the object that the billboard will rotate around.</param>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraUpVector">The up vector of the camera.</param>
    /// <param name="cameraForwardVector">The forward vector of the camera.</param>
    /// <returns>The created billboard.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateBillboard(Vector3 objectPosition, Vector3 cameraPosition, Vector3 cameraUpVector, Vector3 cameraForwardVector) => System.Numerics.Matrix4x4.CreateBillboard(objectPosition, cameraPosition, cameraUpVector, cameraForwardVector);

    /// <summary>Creates a left-handed spherical billboard matrix that rotates around a specified object position.</summary>
    /// <param name="objectPosition">The position of the object that the billboard will rotate around.</param>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraUpVector">The up vector of the camera.</param>
    /// <param name="cameraForwardVector">The forward vector of the camera.</param>
    /// <returns>The created billboard.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateBillboardLeftHanded(Vector3 objectPosition, Vector3 cameraPosition, Vector3 cameraUpVector, Vector3 cameraForwardVector) => System.Numerics.Matrix4x4.CreateBillboardLeftHanded(objectPosition, cameraPosition, cameraUpVector, cameraForwardVector);

    /// <summary>Creates a cylindrical billboard that rotates around a specified axis.</summary>
    /// <param name="objectPosition">The position of the object that the billboard will rotate around.</param>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="rotateAxis">The axis to rotate the billboard around.</param>
    /// <param name="cameraForwardVector">The forward vector of the camera.</param>
    /// <param name="objectForwardVector">The forward vector of the object.</param>
    /// <returns>The billboard matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateConstrainedBillboard(Vector3 objectPosition, Vector3 cameraPosition, Vector3 rotateAxis, Vector3 cameraForwardVector, Vector3 objectForwardVector) => System.Numerics.Matrix4x4.CreateConstrainedBillboard(objectPosition, cameraPosition, rotateAxis, cameraForwardVector, objectForwardVector);

    /// <summary>Creates a left-handed cylindrical billboard matrix that rotates around a specified axis.</summary>
    /// <param name="objectPosition">The position of the object that the billboard will rotate around.</param>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="rotateAxis">The axis to rotate the billboard around.</param>
    /// <param name="cameraForwardVector">The forward vector of the camera.</param>
    /// <param name="objectForwardVector">The forward vector of the object.</param>
    /// <returns>The billboard matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateConstrainedBillboardLeftHanded(Vector3 objectPosition, Vector3 cameraPosition, Vector3 rotateAxis, Vector3 cameraForwardVector, Vector3 objectForwardVector) => System.Numerics.Matrix4x4.CreateConstrainedBillboardLeftHanded(objectPosition, cameraPosition, rotateAxis, cameraForwardVector, objectForwardVector);

    /// <summary>Creates a matrix that rotates around an arbitrary vector.</summary>
    /// <param name="axis">The axis to rotate around.</param>
    /// <param name="angle">The angle to rotate around <paramref name="axis" />, in radians.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateFromAxisAngle(Vector3 axis, float angle) => System.Numerics.Matrix4x4.CreateFromAxisAngle(axis, angle);

    /// <summary>Creates a rotation matrix from the specified Quaternion rotation value.</summary>
    /// <param name="quaternion">The source Quaternion.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateFromQuaternion(System.Numerics.Quaternion quaternion) => System.Numerics.Matrix4x4.CreateFromQuaternion(quaternion);

    /// <summary>Creates a rotation matrix from the specified yaw, pitch, and roll.</summary>
    /// <param name="yaw">The angle of rotation, in radians, around the Y axis.</param>
    /// <param name="pitch">The angle of rotation, in radians, around the X axis.</param>
    /// <param name="roll">The angle of rotation, in radians, around the Z axis.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateFromYawPitchRoll(float yaw, float pitch, float roll) => System.Numerics.Matrix4x4.CreateFromYawPitchRoll(yaw, pitch, roll);

    /// <summary>Creates a view matrix.</summary>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraTarget">The target towards which the camera is pointing.</param>
    /// <param name="cameraUpVector">The direction that is "up" from the camera's point of view.</param>
    /// <returns>The view matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateLookAt(Vector3 cameraPosition, Vector3 cameraTarget, Vector3 cameraUpVector) => System.Numerics.Matrix4x4.CreateLookAt(cameraPosition, cameraTarget, cameraUpVector);

    /// <summary>Creates a left-handed view matrix.</summary>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraTarget">The target towards which the camera is pointing.</param>
    /// <param name="cameraUpVector">The direction that is "up" from the camera's point of view.</param>
    /// <returns>The left-handed view matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateLookAtLeftHanded(Vector3 cameraPosition, Vector3 cameraTarget, Vector3 cameraUpVector) => System.Numerics.Matrix4x4.CreateLookAtLeftHanded(cameraPosition, cameraTarget, cameraUpVector);

    /// <summary>Creates a right-handed view matrix.</summary>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraDirection">The direction in which the camera is pointing.</param>
    /// <param name="cameraUpVector">The direction that is "up" from the camera's point of view.</param>
    /// <returns>The right-handed view matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateLookTo(Vector3 cameraPosition, Vector3 cameraDirection, Vector3 cameraUpVector) => System.Numerics.Matrix4x4.CreateLookTo(cameraPosition, cameraDirection, cameraUpVector);

    /// <summary>Creates a left-handed view matrix.</summary>
    /// <param name="cameraPosition">The position of the camera.</param>
    /// <param name="cameraDirection">The direction in which the camera is pointing.</param>
    /// <param name="cameraUpVector">The direction that is "up" from the camera's point of view.</param>
    /// <returns>The left-handed view matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateLookToLeftHanded(Vector3 cameraPosition, Vector3 cameraDirection, Vector3 cameraUpVector) => System.Numerics.Matrix4x4.CreateLookToLeftHanded(cameraPosition, cameraDirection, cameraUpVector);

    /// <summary>Creates an orthographic perspective matrix from the given view volume dimensions.</summary>
    /// <param name="width">The width of the view volume.</param>
    /// <param name="height">The height of the view volume.</param>
    /// <param name="zNearPlane">The minimum Z-value of the view volume.</param>
    /// <param name="zFarPlane">The maximum Z-value of the view volume.</param>
    /// <returns>The orthographic projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateOrthographic(float width, float height, float zNearPlane, float zFarPlane) => System.Numerics.Matrix4x4.CreateOrthographic(width, height, zNearPlane, zFarPlane);

    /// <summary>Creates a left-handed orthographic perspective matrix from the given view volume dimensions.</summary>
    /// <param name="width">The width of the view volume.</param>
    /// <param name="height">The height of the view volume.</param>
    /// <param name="zNearPlane">The minimum Z-value of the view volume.</param>
    /// <param name="zFarPlane">The maximum Z-value of the view volume.</param>
    /// <returns>The left-handed orthographic projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateOrthographicLeftHanded(float width, float height, float zNearPlane, float zFarPlane) => System.Numerics.Matrix4x4.CreateOrthographicLeftHanded(width, height, zNearPlane, zFarPlane);

    /// <summary>Creates a customized orthographic projection matrix.</summary>
    /// <param name="left">The minimum X-value of the view volume.</param>
    /// <param name="right">The maximum X-value of the view volume.</param>
    /// <param name="bottom">The minimum Y-value of the view volume.</param>
    /// <param name="top">The maximum Y-value of the view volume.</param>
    /// <param name="zNearPlane">The minimum Z-value of the view volume.</param>
    /// <param name="zFarPlane">The maximum Z-value of the view volume.</param>
    /// <returns>The orthographic projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateOrthographicOffCenter(float left, float right, float bottom, float top, float zNearPlane, float zFarPlane) => System.Numerics.Matrix4x4.CreateOrthographicOffCenter(left, right, bottom, top, zNearPlane, zFarPlane);

    /// <summary>Creates a left-handed customized orthographic projection matrix.</summary>
    /// <param name="left">The minimum X-value of the view volume.</param>
    /// <param name="right">The maximum X-value of the view volume.</param>
    /// <param name="bottom">The minimum Y-value of the view volume.</param>
    /// <param name="top">The maximum Y-value of the view volume.</param>
    /// <param name="zNearPlane">The minimum Z-value of the view volume.</param>
    /// <param name="zFarPlane">The maximum Z-value of the view volume.</param>
    /// <returns>The left-handed orthographic projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateOrthographicOffCenterLeftHanded(float left, float right, float bottom, float top, float zNearPlane, float zFarPlane) => System.Numerics.Matrix4x4.CreateOrthographicOffCenterLeftHanded(left, right, bottom, top, zNearPlane, zFarPlane);

    /// <summary>Creates a perspective projection matrix from the given view volume dimensions.</summary>
    /// <param name="width">The width of the view volume at the near view plane.</param>
    /// <param name="height">The height of the view volume at the near view plane.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspective(float width, float height, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspective(width, height, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a left-handed perspective projection matrix from the given view volume dimensions.</summary>
    /// <param name="width">The width of the view volume at the near view plane.</param>
    /// <param name="height">The height of the view volume at the near view plane.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The left-handed perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspectiveLeftHanded(float width, float height, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspectiveLeftHanded(width, height, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a perspective projection matrix based on a field of view, aspect ratio, and near and far view plane distances.</summary>
    /// <param name="fieldOfView">The field of view in the y direction, in radians.</param>
    /// <param name="aspectRatio">The aspect ratio, defined as view space width divided by height.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="fieldOfView" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="fieldOfView" /> is greater than or equal to <see cref="F:System.Math.PI" />.
    /// <paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspectiveFieldOfView(float fieldOfView, float aspectRatio, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspectiveFieldOfView(fieldOfView, aspectRatio, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a left-handed perspective projection matrix based on a field of view, aspect ratio, and near and far view plane distances.</summary>
    /// <param name="fieldOfView">The field of view in the y direction, in radians.</param>
    /// <param name="aspectRatio">The aspect ratio, defined as view space width divided by height.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="fieldOfView" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="fieldOfView" /> is greater than or equal to <see cref="F:System.Math.PI" />.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The left-handed perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspectiveFieldOfViewLeftHanded(float fieldOfView, float aspectRatio, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspectiveFieldOfViewLeftHanded(fieldOfView, aspectRatio, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a customized perspective projection matrix.</summary>
    /// <param name="left">The minimum x-value of the view volume at the near view plane.</param>
    /// <param name="right">The maximum x-value of the view volume at the near view plane.</param>
    /// <param name="bottom">The minimum y-value of the view volume at the near view plane.</param>
    /// <param name="top">The maximum y-value of the view volume at the near view plane.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspectiveOffCenter(float left, float right, float bottom, float top, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspectiveOffCenter(left, right, bottom, top, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a left-handed customized perspective projection matrix.</summary>
    /// <param name="left">The minimum x-value of the view volume at the near view plane.</param>
    /// <param name="right">The maximum x-value of the view volume at the near view plane.</param>
    /// <param name="bottom">The minimum y-value of the view volume at the near view plane.</param>
    /// <param name="top">The maximum y-value of the view volume at the near view plane.</param>
    /// <param name="nearPlaneDistance">The distance to the near view plane.</param>
    /// <param name="farPlaneDistance">The distance to the far view plane.</param>
    /// <exception cref="T:System.ArgumentOutOfRangeException"><paramref name="nearPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="farPlaneDistance" /> is less than or equal to zero.
    /// -or-
    /// <paramref name="nearPlaneDistance" /> is greater than or equal to <paramref name="farPlaneDistance" />.</exception>
    /// <returns>The left-handed perspective projection matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreatePerspectiveOffCenterLeftHanded(float left, float right, float bottom, float top, float nearPlaneDistance, float farPlaneDistance) => System.Numerics.Matrix4x4.CreatePerspectiveOffCenterLeftHanded(left, right, bottom, top, nearPlaneDistance, farPlaneDistance);

    /// <summary>Creates a matrix that reflects the coordinate system about a specified plane.</summary>
    /// <param name="value">The plane about which to create a reflection.</param>
    /// <returns>A new matrix expressing the reflection.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateReflection(System.Numerics.Plane value) => System.Numerics.Matrix4x4.CreateReflection(value);

    /// <summary>Creates a matrix for rotating points around the X axis.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the X axis.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationX(float radians) => System.Numerics.Matrix4x4.CreateRotationX(radians);

    /// <summary>Creates a matrix for rotating points around the X axis from a center point.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the X axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationX(float radians, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateRotationX(radians, centerPoint);

    /// <summary>Creates a matrix for rotating points around the Y axis.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the Y-axis.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationY(float radians) => System.Numerics.Matrix4x4.CreateRotationY(radians);

    /// <summary>The amount, in radians, by which to rotate around the Y axis from a center point.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the Y-axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationY(float radians, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateRotationY(radians, centerPoint);

    /// <summary>Creates a matrix for rotating points around the Z axis.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the Z-axis.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationZ(float radians) => System.Numerics.Matrix4x4.CreateRotationZ(radians);

    /// <summary>Creates a matrix for rotating points around the Z axis from a center point.</summary>
    /// <param name="radians">The amount, in radians, by which to rotate around the Z-axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The rotation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateRotationZ(float radians, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateRotationZ(radians, centerPoint);

    /// <summary>Creates a scaling matrix from the specified vector scale.</summary>
    /// <param name="scales">The scale to use.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(Vector3 scales) => System.Numerics.Matrix4x4.CreateScale(scales);

    /// <summary>Creates a scaling matrix with a center point.</summary>
    /// <param name="scales">The vector that contains the amount to scale on each axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(Vector3 scales, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateScale(scales, centerPoint);

    /// <summary>Creates a uniform scaling matrix that scale equally on each axis.</summary>
    /// <param name="scale">The uniform scaling factor.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(float scale) => System.Numerics.Matrix4x4.CreateScale(scale);

    /// <summary>Creates a uniform scaling matrix that scales equally on each axis with a center point.</summary>
    /// <param name="scale">The uniform scaling factor.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(float scale, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateScale(scale, centerPoint);

    /// <summary>Creates a scaling matrix from the specified X, Y, and Z components.</summary>
    /// <param name="xScale">The value to scale by on the X axis.</param>
    /// <param name="yScale">The value to scale by on the Y axis.</param>
    /// <param name="zScale">The value to scale by on the Z axis.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(float xScale, float yScale, float zScale) => System.Numerics.Matrix4x4.CreateScale(xScale, yScale, zScale);

    /// <summary>Creates a scaling matrix that is offset by a given center point.</summary>
    /// <param name="xScale">The value to scale by on the X axis.</param>
    /// <param name="yScale">The value to scale by on the Y axis.</param>
    /// <param name="zScale">The value to scale by on the Z axis.</param>
    /// <param name="centerPoint">The center point.</param>
    /// <returns>The scaling matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateScale(float xScale, float yScale, float zScale, Vector3 centerPoint) => System.Numerics.Matrix4x4.CreateScale(xScale, yScale, zScale, centerPoint);

    /// <summary>Creates a matrix that flattens geometry into a specified plane as if casting a shadow from a specified light source.</summary>
    /// <param name="lightDirection">The direction from which the light that will cast the shadow is coming.</param>
    /// <param name="plane">The plane onto which the new matrix should flatten geometry so as to cast a shadow.</param>
    /// <returns>A new matrix that can be used to flatten geometry onto the specified plane from the specified direction.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateShadow(Vector3 lightDirection, System.Numerics.Plane plane) => System.Numerics.Matrix4x4.CreateShadow(lightDirection, plane);

    /// <summary>Creates a translation matrix from the specified 3-dimensional vector.</summary>
    /// <param name="position">The amount to translate in each axis.</param>
    /// <returns>The translation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateTranslation(Vector3 position) => System.Numerics.Matrix4x4.CreateTranslation(position);

    /// <summary>Creates a translation matrix from the specified X, Y, and Z components.</summary>
    /// <param name="xPosition">The amount to translate on the X axis.</param>
    /// <param name="yPosition">The amount to translate on the Y axis.</param>
    /// <param name="zPosition">The amount to translate on the Z axis.</param>
    /// <returns>The translation matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateTranslation(float xPosition, float yPosition, float zPosition) => System.Numerics.Matrix4x4.CreateTranslation(xPosition, yPosition, zPosition);

    /// <summary>Creates a right-handed viewport matrix from the specified parameters.</summary>
    /// <param name="x">X coordinate of the viewport upper left corner.</param>
    /// <param name="y">Y coordinate of the viewport upper left corner.</param>
    /// <param name="width">Viewport width.</param>
    /// <param name="height">Viewport height.</param>
    /// <param name="minDepth">Viewport minimum depth.</param>
    /// <param name="maxDepth">Viewport maximum depth.</param>
    /// <returns>The right-handed viewport matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateViewport(float x, float y, float width, float height, float minDepth, float maxDepth) => System.Numerics.Matrix4x4.CreateViewport(x, y, width, height, minDepth, maxDepth);

    /// <summary>Creates a left-handed viewport matrix from the specified parameters.</summary>
    /// <param name="x">X coordinate of the viewport upper left corner.</param>
    /// <param name="y">Y coordinate of the viewport upper left corner.</param>
    /// <param name="width">Viewport width.</param>
    /// <param name="height">Viewport height.</param>
    /// <param name="minDepth">Viewport minimum depth.</param>
    /// <param name="maxDepth">Viewport maximum depth.</param>
    /// <returns>The left-handed viewport matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateViewportLeftHanded(float x, float y, float width, float height, float minDepth, float maxDepth) => System.Numerics.Matrix4x4.CreateViewportLeftHanded(x, y, width, height, minDepth, maxDepth);

    /// <summary>Creates a world matrix with the specified parameters.</summary>
    /// <param name="position">The position of the object.</param>
    /// <param name="forward">The forward direction of the object.</param>
    /// <param name="up">The upward direction of the object. Its value is usually <c>[0, 1, 0]</c>.</param>
    /// <returns>The world matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 CreateWorld(Vector3 position, Vector3 forward, Vector3 up) => System.Numerics.Matrix4x4.CreateWorld(position, forward, up);

    /// <summary>Attempts to extract the scale, translation, and rotation components from the given scale, rotation, or translation matrix. The return value indicates whether the operation succeeded.</summary>
    /// <param name="matrix">The source matrix.</param>
    /// <param name="scale">When this method returns, contains the scaling component of the transformation matrix if the operation succeeded.</param>
    /// <param name="rotation">When this method returns, contains the rotation component of the transformation matrix if the operation succeeded.</param>
    /// <param name="translation">When the method returns, contains the translation component of the transformation matrix if the operation succeeded.</param>
    /// <returns><see langword="true" /> if <paramref name="matrix" /> was decomposed successfully; otherwise,  <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool Decompose(Matrix4x4 matrix, out Vector3 scale, out System.Numerics.Quaternion rotation, out Vector3 translation)
    {
        System.Numerics.Vector3 scaleUnderlying;
        System.Numerics.Quaternion rotationUnderlying;
        System.Numerics.Vector3 translationUnderlying;
        var returnValue = System.Numerics.Matrix4x4.Decompose(matrix, out scaleUnderlying, out rotationUnderlying, out translationUnderlying);
        scale = scaleUnderlying;
        rotation = rotationUnderlying;
        translation = translationUnderlying;
        return returnValue;
    }

    /// <summary>Inverts the specified matrix. The return value indicates whether the operation succeeded.</summary>
    /// <param name="matrix">The matrix to invert.</param>
    /// <param name="result">When this method returns, contains the inverted matrix if the operation succeeded.</param>
    /// <returns><see langword="true" /> if <paramref name="matrix" /> was converted successfully; otherwise,  <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool Invert(Matrix4x4 matrix, out Matrix4x4 result)
    {
        System.Numerics.Matrix4x4 resultUnderlying;
        var returnValue = System.Numerics.Matrix4x4.Invert(matrix, out resultUnderlying);
        result = resultUnderlying;
        return returnValue;
    }

    /// <summary>Performs a linear interpolation from one matrix to a second matrix based on a value that specifies the weighting of the second matrix.</summary>
    /// <param name="matrix1">The first matrix.</param>
    /// <param name="matrix2">The second matrix.</param>
    /// <param name="amount">The relative weighting of <paramref name="matrix2" />.</param>
    /// <returns>The interpolated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Lerp(Matrix4x4 matrix1, Matrix4x4 matrix2, float amount) => System.Numerics.Matrix4x4.Lerp(matrix1, matrix2, amount);

    /// <summary>Returns the matrix that results from multiplying two matrices together.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The product matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Multiply(Matrix4x4 value1, Matrix4x4 value2) => System.Numerics.Matrix4x4.Multiply(value1, value2);

    /// <summary>Returns the matrix that results from scaling all the elements of a specified matrix by a scalar factor.</summary>
    /// <param name="value1">The matrix to scale.</param>
    /// <param name="value2">The scaling value to use.</param>
    /// <returns>The scaled matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Multiply(Matrix4x4 value1, float value2) => System.Numerics.Matrix4x4.Multiply(value1, value2);

    /// <summary>Negates the specified matrix by multiplying all its values by -1.</summary>
    /// <param name="value">The matrix to negate.</param>
    /// <returns>The negated matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Negate(Matrix4x4 value) => System.Numerics.Matrix4x4.Negate(value);

    /// <summary>Subtracts each element in a second matrix from its corresponding element in a first matrix.</summary>
    /// <param name="value1">The first matrix.</param>
    /// <param name="value2">The second matrix.</param>
    /// <returns>The matrix containing the values that result from subtracting each element in <paramref name="value2" /> from its corresponding element in <paramref name="value1" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Subtract(Matrix4x4 value1, Matrix4x4 value2) => System.Numerics.Matrix4x4.Subtract(value1, value2);

    /// <summary>Transforms the specified matrix by applying the specified Quaternion rotation.</summary>
    /// <param name="value">The matrix to transform.</param>
    /// <param name="rotation">The rotation t apply.</param>
    /// <returns>The transformed matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Transform(Matrix4x4 value, System.Numerics.Quaternion rotation) => System.Numerics.Matrix4x4.Transform(value, rotation);

    /// <summary>Transposes the rows and columns of a matrix.</summary>
    /// <param name="matrix">The matrix to transpose.</param>
    /// <returns>The transposed matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Matrix4x4 Transpose(Matrix4x4 matrix) => System.Numerics.Matrix4x4.Transpose(matrix);

    /// <summary>Calculates the determinant of the current 4x4 matrix.</summary>
    /// <returns>The determinant.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float GetDeterminant() => this.Value.GetDeterminant();

    /// <summary>Returns a string that represents this matrix.</summary>
    /// <returns>The string representation of this matrix.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override string ToString() => this.Value.ToString();

    /// <summary>Indicates whether the current object is equal to another object of the same type.</summary>
    /// <param name="other">An object to compare with this object.</param>
    /// <returns><c>true</c> if the current object is equal to the <paramref name="other" /> parameter; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Matrix4x4 other) => this.Value.Equals(other.Value);

    /// <summary>Indicates whether this instance and a specified object are equal.</summary>
    /// <param name="obj">The object to compare with the current instance.</param>
    /// <returns><c>true</c> if <paramref name="obj" /> and this instance are the same type and represent the same value; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object obj) => obj is Matrix4x4 other && Equals(other);

    /// <summary>Returns the hash code for this instance.</summary>
    /// <returns>A 32-bit signed integer that is the hash code for this instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode() => this.Value.GetHashCode();
}
