// <auto-generated>
// This code is generated by the Sakura framework source generator.
// Generator name : Sakura.Framework.SourceGenerators.Generators.MathStructGenerator
// Type wrapper for System.Numerics.Vector3 for Vector3
// Last updated : 2026-06-01 06:58:53 UTC
// </auto-generated>
namespace Sakura.Framework.Maths;

public partial struct Vector3 : System.IEquatable<Vector3>
{
    /// <summary>Creates a   new <see cref="T:System.Numerics.Vector3" /> object from the specified <see cref="T:System.Numerics.Vector2" /> object and the specified value.</summary>
    /// <param name="value">The vector with two elements.</param>
    /// <param name="z">The additional value to assign to the <see cref="F:System.Numerics.Vector3.Z" /> field.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector3(Vector2 value, float z)
    {
        this.Value = new System.Numerics.Vector3(value, z);
    }

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector3" /> object whose three elements have the same value.</summary>
    /// <param name="value">The value to assign to all three elements.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector3(float value)
    {
        this.Value = new System.Numerics.Vector3(value);
    }

    /// <summary>Creates a vector whose elements have the specified values.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector3.X" /> field.</param>
    /// <param name="y">The value to assign to the <see cref="F:System.Numerics.Vector3.Y" /> field.</param>
    /// <param name="z">The value to assign to the <see cref="F:System.Numerics.Vector3.Z" /> field.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector3(float x, float y, float z)
    {
        this.Value = new System.Numerics.Vector3(x, y, z);
    }

    /// <summary>Constructs a vector from the given <see cref="T:System.ReadOnlySpan`1" />. The span must contain at least 3 elements.</summary>
    /// <param name="values">The span of elements to assign to the vector.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector3(System.ReadOnlySpan<float> values)
    {
        this.Value = new System.Numerics.Vector3(values);
    }

    /// <summary>Adds two vectors together.</summary>
    /// <param name="left">The first vector to add.</param>
    /// <param name="right">The second vector to add.</param>
    /// <returns>The summed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator +(Vector3 left, Vector3 right) => left.Value + right.Value;

    /// <summary>Divides the first vector by the second.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector that results from dividing <paramref name="left" /> by <paramref name="right" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator /(Vector3 left, Vector3 right) => left.Value / right.Value;

    /// <summary>Divides the specified vector by a specified scalar value.</summary>
    /// <param name="value1">The vector.</param>
    /// <param name="value2">The scalar value.</param>
    /// <returns>The result of the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator /(Vector3 value1, float value2) => value1.Value / value2;

    /// <summary>Returns a value that indicates whether each pair of elements in two specified vectors is equal.</summary>
    /// <param name="left">The first vector to compare.</param>
    /// <param name="right">The second vector to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="left" /> and <paramref name="right" /> are equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Vector3 left, Vector3 right) => left.Value == right.Value;

    /// <summary>Returns a value that indicates whether two specified vectors are not equal.</summary>
    /// <param name="left">The first vector to compare.</param>
    /// <param name="right">The second vector to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="left" /> and <paramref name="right" /> are not equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Vector3 left, Vector3 right) => left.Value != right.Value;

    /// <summary>Returns a new vector whose values are the product of each pair of elements in two specified vectors.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The element-wise product vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator *(Vector3 left, Vector3 right) => left.Value * right.Value;

    /// <summary>Multiples the specified vector by the specified scalar value.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator *(Vector3 left, float right) => left.Value * right;

    /// <summary>Multiples the scalar value by the specified vector.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator *(float left, Vector3 right) => left * right.Value;

    /// <summary>Subtracts the second vector from the first.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector that results from subtracting <paramref name="right" /> from <paramref name="left" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator -(Vector3 left, Vector3 right) => left.Value - right.Value;

    /// <summary>Negates the specified vector.</summary>
    /// <param name="value">The vector to negate.</param>
    /// <returns>The negated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 operator -(Vector3 value) => -value.Value;

    /// <summary>Returns a vector whose elements are the absolute values of each of the specified vector's elements.</summary>
    /// <param name="value">A vector.</param>
    /// <returns>The absolute value vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Abs(Vector3 value) => System.Numerics.Vector3.Abs(value);

    /// <summary>Adds two vectors together.</summary>
    /// <param name="left">The first vector to add.</param>
    /// <param name="right">The second vector to add.</param>
    /// <returns>The summed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Add(Vector3 left, Vector3 right) => System.Numerics.Vector3.Add(left, right);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool All(Vector3 vector, float value) => System.Numerics.Vector3.All(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool AllWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.AllWhereAllBitsSet(vector);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 AndNot(Vector3 left, Vector3 right) => System.Numerics.Vector3.AndNot(left, right);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool Any(Vector3 vector, float value) => System.Numerics.Vector3.Any(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool AnyWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.AnyWhereAllBitsSet(vector);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 BitwiseAnd(Vector3 left, Vector3 right) => System.Numerics.Vector3.BitwiseAnd(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 BitwiseOr(Vector3 left, Vector3 right) => System.Numerics.Vector3.BitwiseOr(left, right);

    /// <summary>Restricts a vector between a minimum and a maximum value.</summary>
    /// <param name="value1">The vector to restrict.</param>
    /// <param name="min">The minimum value.</param>
    /// <param name="max">The maximum value.</param>
    /// <returns>The restricted vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Clamp(Vector3 value1, Vector3 min, Vector3 max) => System.Numerics.Vector3.Clamp(value1, min, max);

    /// <summary>Restricts a vector between a minimum and a maximum value using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>..</summary>
    /// <param name="value1" />
    /// <param name="min">The minimum value.</param>
    /// <param name="max">The maximum value.</param>
    /// <returns>The restricted vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 ClampNative(Vector3 value1, Vector3 min, Vector3 max) => System.Numerics.Vector3.ClampNative(value1, min, max);

    /// <param name="condition" />
    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 ConditionalSelect(Vector3 condition, Vector3 left, Vector3 right) => System.Numerics.Vector3.ConditionalSelect(condition, left, right);

    /// <summary>Copies the per-element sign of a vector to the per-element sign of another vector.</summary>
    /// <param name="value">The vector whose magnitude is used in the result.</param>
    /// <param name="sign">The vector whose sign is used in the result.</param>
    /// <returns>A vector with the magnitude of <code data-dev-comment-type="paramref">value</code> and the sign of <code data-dev-comment-type="paramref">sign</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 CopySign(Vector3 value, Vector3 sign) => System.Numerics.Vector3.CopySign(value, sign);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Count(Vector3 vector, float value) => System.Numerics.Vector3.Count(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int CountWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.CountWhereAllBitsSet(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Cos(Vector3 vector) => System.Numerics.Vector3.Cos(vector);

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector3" /> object whose three elements have the same value.</summary>
    /// <param name="value">The value to assign to all three elements.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> whose three elements have the same value.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Create(float value) => System.Numerics.Vector3.Create(value);

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector3" /> object from the specified <see cref="T:System.Numerics.Vector2" /> object and a Z component.</summary>
    /// <param name="vector">The vector to use for the X and Y components.</param>
    /// <param name="z">The Z component.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> from the specified <see cref="T:System.Numerics.Vector2" /> object and a Z component.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Create(Vector2 vector, float z) => System.Numerics.Vector3.Create(vector, z);

    /// <summary>Creates a vector whose elements have the specified values.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector3.X" /> field.</param>
    /// <param name="y">The value to assign to the <see cref="F:System.Numerics.Vector3.Y" /> field.</param>
    /// <param name="z">The value to assign to the <see cref="F:System.Numerics.Vector3.Z" /> field.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> whose elements have the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Create(float x, float y, float z) => System.Numerics.Vector3.Create(x, y, z);

    /// <summary>Constructs a vector from the given <see cref="T:System.ReadOnlySpan`1" />. The span must contain at least 3 elements.</summary>
    /// <param name="values">The span of elements to assign to the vector.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> whose elements have the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Create(System.ReadOnlySpan<float> values) => System.Numerics.Vector3.Create(values);

    /// <summary>Creates a vector with <see cref="F:System.Numerics.Vector3.X" /> initialized to the specified value and the remaining elements initialized to zero.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector3.X" /> field.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> with <see cref="F:System.Numerics.Vector3.X" /> initialized <paramref name="x" /> and the remaining elements initialized to zero.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 CreateScalar(float x) => System.Numerics.Vector3.CreateScalar(x);

    /// <summary>Creates a vector with <see cref="F:System.Numerics.Vector3.X" /> initialized to the specified value and the remaining elements left uninitialized.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector3.X" /> field.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector3" /> with <see cref="F:System.Numerics.Vector3.X" /> initialized <paramref name="x" /> and the remaining elements left uninitialized.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 CreateScalarUnsafe(float x) => System.Numerics.Vector3.CreateScalarUnsafe(x);

    /// <summary>Computes the cross product of two vectors.</summary>
    /// <param name="vector1">The first vector.</param>
    /// <param name="vector2">The second vector.</param>
    /// <returns>The cross product.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Cross(Vector3 vector1, Vector3 vector2) => System.Numerics.Vector3.Cross(vector1, vector2);

    /// <param name="degrees" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 DegreesToRadians(Vector3 degrees) => System.Numerics.Vector3.DegreesToRadians(degrees);

    /// <summary>Computes the Euclidean distance between the two given points.</summary>
    /// <param name="value1">The first point.</param>
    /// <param name="value2">The second point.</param>
    /// <returns>The distance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Distance(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.Distance(value1, value2);

    /// <summary>Returns the Euclidean distance squared between two specified points.</summary>
    /// <param name="value1">The first point.</param>
    /// <param name="value2">The second point.</param>
    /// <returns>The distance squared.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float DistanceSquared(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.DistanceSquared(value1, value2);

    /// <summary>Divides the first vector by the second.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector resulting from the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Divide(Vector3 left, Vector3 right) => System.Numerics.Vector3.Divide(left, right);

    /// <summary>Divides the specified vector by a specified scalar value.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="divisor">The scalar value.</param>
    /// <returns>The vector that results from the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Divide(Vector3 left, float divisor) => System.Numerics.Vector3.Divide(left, divisor);

    /// <summary>Returns the dot product of two vectors.</summary>
    /// <param name="vector1">The first vector.</param>
    /// <param name="vector2">The second vector.</param>
    /// <returns>The dot product.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Dot(Vector3 vector1, Vector3 vector2) => System.Numerics.Vector3.Dot(vector1, vector2);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Equals(Vector3 left, Vector3 right) => System.Numerics.Vector3.Equals(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool EqualsAll(Vector3 left, Vector3 right) => System.Numerics.Vector3.EqualsAll(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool EqualsAny(Vector3 left, Vector3 right) => System.Numerics.Vector3.EqualsAny(left, right);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Exp(Vector3 vector) => System.Numerics.Vector3.Exp(vector);

    /// <param name="left" />
    /// <param name="right" />
    /// <param name="addend" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 FusedMultiplyAdd(Vector3 left, Vector3 right, Vector3 addend) => System.Numerics.Vector3.FusedMultiplyAdd(left, right, addend);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 GreaterThan(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThan(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanAll(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThanAll(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanAny(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThanAny(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 GreaterThanOrEqual(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThanOrEqual(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanOrEqualAll(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThanOrEqualAll(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanOrEqualAny(Vector3 left, Vector3 right) => System.Numerics.Vector3.GreaterThanOrEqualAny(left, right);

    /// <param name="x" />
    /// <param name="y" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Hypot(Vector3 x, Vector3 y) => System.Numerics.Vector3.Hypot(x, y);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IndexOf(Vector3 vector, float value) => System.Numerics.Vector3.IndexOf(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IndexOfWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.IndexOfWhereAllBitsSet(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsEvenInteger(Vector3 vector) => System.Numerics.Vector3.IsEvenInteger(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsFinite(Vector3 vector) => System.Numerics.Vector3.IsFinite(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsInfinity(Vector3 vector) => System.Numerics.Vector3.IsInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsInteger(Vector3 vector) => System.Numerics.Vector3.IsInteger(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsNaN(Vector3 vector) => System.Numerics.Vector3.IsNaN(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsNegative(Vector3 vector) => System.Numerics.Vector3.IsNegative(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsNegativeInfinity(Vector3 vector) => System.Numerics.Vector3.IsNegativeInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsNormal(Vector3 vector) => System.Numerics.Vector3.IsNormal(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsOddInteger(Vector3 vector) => System.Numerics.Vector3.IsOddInteger(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsPositive(Vector3 vector) => System.Numerics.Vector3.IsPositive(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsPositiveInfinity(Vector3 vector) => System.Numerics.Vector3.IsPositiveInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsSubnormal(Vector3 vector) => System.Numerics.Vector3.IsSubnormal(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 IsZero(Vector3 vector) => System.Numerics.Vector3.IsZero(vector);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int LastIndexOf(Vector3 vector, float value) => System.Numerics.Vector3.LastIndexOf(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int LastIndexOfWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.LastIndexOfWhereAllBitsSet(vector);

    /// <summary>Performs a linear interpolation between two vectors based on the given weighting.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <param name="amount">A value between 0 and 1 that indicates the weight of <code data-dev-comment-type="paramref">value2</code>.</param>
    /// <returns>The interpolated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Lerp(Vector3 value1, Vector3 value2, float amount) => System.Numerics.Vector3.Lerp(value1, value2, amount);

    /// <param name="value1" />
    /// <param name="value2" />
    /// <param name="amount" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Lerp(Vector3 value1, Vector3 value2, Vector3 amount) => System.Numerics.Vector3.Lerp(value1, value2, amount);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 LessThan(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThan(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanAll(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThanAll(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanAny(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThanAny(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 LessThanOrEqual(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThanOrEqual(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanOrEqualAll(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThanOrEqualAll(left, right);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanOrEqualAny(Vector3 left, Vector3 right) => System.Numerics.Vector3.LessThanOrEqualAny(left, right);

    /// <param name="source" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector3 Load(float* source) => System.Numerics.Vector3.Load(source);

    /// <param name="source" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector3 LoadAligned(float* source) => System.Numerics.Vector3.LoadAligned(source);

    /// <param name="source" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector3 LoadAlignedNonTemporal(float* source) => System.Numerics.Vector3.LoadAlignedNonTemporal(source);

    /// <summary>Loads a vector from the given source.</summary>
    /// <param name="source">The source from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 LoadUnsafe(float source) => System.Numerics.Vector3.LoadUnsafe(source);

    /// <param name="source" />
    /// <param name="elementOffset" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 LoadUnsafe(float source, nuint elementOffset) => System.Numerics.Vector3.LoadUnsafe(source, elementOffset);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Log(Vector3 vector) => System.Numerics.Vector3.Log(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Log2(Vector3 vector) => System.Numerics.Vector3.Log2(vector);

    /// <summary>Returns a vector whose elements are the maximum of each of the pairs of elements in two specified vectors.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <returns>The maximized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Max(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.Max(value1, value2);

    /// <summary>Compares two vectors to compute which has the greater magnitude on a per-element basis.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a greater magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MaxMagnitude(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MaxMagnitude(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which has the greater magnitude and returning the other value if an input is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a greater magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MaxMagnitudeNumber(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MaxMagnitudeNumber(value1, value2);

    /// <summary>Compare two vectors to determine which is greater on a per-element basis using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is greater than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MaxNative(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MaxNative(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which is greater and returning the other value if an element is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is greater than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MaxNumber(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MaxNumber(value1, value2);

    /// <summary>Returns a vector whose elements are the minimum of each of the pairs of elements in two specified vectors.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <returns>The minimized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Min(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.Min(value1, value2);

    /// <summary>Compares two vectors to compute which has the lesser magnitude on a per-element basis.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a lesser magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MinMagnitude(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MinMagnitude(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which has the lesser magnitude and returning the other value if an input is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a lesser magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MinMagnitudeNumber(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MinMagnitudeNumber(value1, value2);

    /// <summary>Compare two vectors to determine which is lesser on a per-element basis using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is lesser than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MinNative(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MinNative(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which is lesser and returning the other value if an element is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is lesser than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MinNumber(Vector3 value1, Vector3 value2) => System.Numerics.Vector3.MinNumber(value1, value2);

    /// <summary>Returns a new vector whose values are the product of each pair of elements in two specified vectors.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The element-wise product vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Multiply(Vector3 left, Vector3 right) => System.Numerics.Vector3.Multiply(left, right);

    /// <summary>Multiplies a vector by a specified scalar.</summary>
    /// <param name="left">The vector to multiply.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Multiply(Vector3 left, float right) => System.Numerics.Vector3.Multiply(left, right);

    /// <summary>Multiplies a scalar value by a specified vector.</summary>
    /// <param name="left">The scaled value.</param>
    /// <param name="right">The vector.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Multiply(float left, Vector3 right) => System.Numerics.Vector3.Multiply(left, right);

    /// <param name="left" />
    /// <param name="right" />
    /// <param name="addend" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 MultiplyAddEstimate(Vector3 left, Vector3 right, Vector3 addend) => System.Numerics.Vector3.MultiplyAddEstimate(left, right, addend);

    /// <summary>Negates a specified vector.</summary>
    /// <param name="value">The vector to negate.</param>
    /// <returns>The negated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Negate(Vector3 value) => System.Numerics.Vector3.Negate(value);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool None(Vector3 vector, float value) => System.Numerics.Vector3.None(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool NoneWhereAllBitsSet(Vector3 vector) => System.Numerics.Vector3.NoneWhereAllBitsSet(vector);

    /// <summary>Returns a vector with the same direction as the specified vector, but with a length of one.</summary>
    /// <param name="value">The vector to normalize.</param>
    /// <returns>The normalized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Normalize(Vector3 value) => System.Numerics.Vector3.Normalize(value);

    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 OnesComplement(Vector3 value) => System.Numerics.Vector3.OnesComplement(value);

    /// <param name="radians" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 RadiansToDegrees(Vector3 radians) => System.Numerics.Vector3.RadiansToDegrees(radians);

    /// <summary>Returns the reflection of a vector off a surface that has the specified normal.</summary>
    /// <param name="vector">The source vector.</param>
    /// <param name="normal">The normal of the surface being reflected off.</param>
    /// <returns>The reflected vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Reflect(Vector3 vector, Vector3 normal) => System.Numerics.Vector3.Reflect(vector, normal);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Round(Vector3 vector) => System.Numerics.Vector3.Round(vector);

    /// <param name="vector" />
    /// <param name="mode" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Round(Vector3 vector, System.MidpointRounding mode) => System.Numerics.Vector3.Round(vector, mode);

    /// <summary>Creates a new vector by selecting values from an input vector using a set of indices.</summary>
    /// <param name="vector">The input vector from which values are selected.</param>
    /// <param name="xIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector3.X" /> in the result.</param>
    /// <param name="yIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector3.Y" /> in the result</param>
    /// <param name="zIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector3.Z" /> in the result</param>
    /// <returns>A new vector containing the values from <paramref name="vector" /> selected by the given indices.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Shuffle(Vector3 vector, byte xIndex, byte yIndex, byte zIndex) => System.Numerics.Vector3.Shuffle(vector, xIndex, yIndex, zIndex);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Sin(Vector3 vector) => System.Numerics.Vector3.Sin(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static (System.Numerics.Vector3 Sin, System.Numerics.Vector3 Cos) SinCos(Vector3 vector) => System.Numerics.Vector3.SinCos(vector);

    /// <summary>Returns a vector whose elements are the square root of each of a specified vector's elements.</summary>
    /// <param name="value">A vector.</param>
    /// <returns>The square root vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 SquareRoot(Vector3 value) => System.Numerics.Vector3.SquareRoot(value);

    /// <summary>Subtracts the second vector from the first.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The difference vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Subtract(Vector3 left, Vector3 right) => System.Numerics.Vector3.Subtract(left, right);

    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Sum(Vector3 value) => System.Numerics.Vector3.Sum(value);

    /// <summary>Transforms a vector by a specified 4x4 matrix.</summary>
    /// <param name="position">The vector to transform.</param>
    /// <param name="matrix">The transformation matrix.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Transform(Vector3 position, Matrix4x4 matrix) => System.Numerics.Vector3.Transform(position, matrix);

    /// <summary>Transforms a vector by the specified Quaternion rotation value.</summary>
    /// <param name="value">The vector to rotate.</param>
    /// <param name="rotation">The rotation to apply.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Transform(Vector3 value, System.Numerics.Quaternion rotation) => System.Numerics.Vector3.Transform(value, rotation);

    /// <summary>Transforms a vector normal by the given 4x4 matrix.</summary>
    /// <param name="normal">The source vector.</param>
    /// <param name="matrix">The matrix.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 TransformNormal(Vector3 normal, Matrix4x4 matrix) => System.Numerics.Vector3.TransformNormal(normal, matrix);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Truncate(Vector3 vector) => System.Numerics.Vector3.Truncate(vector);

    /// <param name="left" />
    /// <param name="right" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector3 Xor(Vector3 left, Vector3 right) => System.Numerics.Vector3.Xor(left, right);

    /// <summary>Returns the length of this vector object.</summary>
    /// <returns>The vector's length.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float Length() => this.Value.Length();

    /// <summary>Returns the length of the vector squared.</summary>
    /// <returns>The vector's length squared.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float LengthSquared() => this.Value.LengthSquared();

    /// <summary>Returns the string representation of the current instance using default formatting.</summary>
    /// <returns>The string representation of the current instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override string ToString() => this.Value.ToString();

    /// <summary>Indicates whether the current object is equal to another object of the same type.</summary>
    /// <param name="other">An object to compare with this object.</param>
    /// <returns><c>true</c> if the current object is equal to the <paramref name="other" /> parameter; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Vector3 other) => this.Value.Equals(other.Value);

    /// <summary>Indicates whether this instance and a specified object are equal.</summary>
    /// <param name="obj">The object to compare with the current instance.</param>
    /// <returns><c>true</c> if <paramref name="obj" /> and this instance are the same type and represent the same value; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object obj) => obj is Vector3 other && Equals(other);

    /// <summary>Returns the hash code for this instance.</summary>
    /// <returns>A 32-bit signed integer that is the hash code for this instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode() => this.Value.GetHashCode();
}
