// <auto-generated>
// This code is generated by the Sakura framework source generator.
// Generator name : Sakura.Framework.SourceGenerators.Generators.MathStructGenerator
// Type wrapper for System.Numerics.Vector4 for Vector4
// Last updated : 2026-06-01 06:58:53 UTC
// </auto-generated>
namespace Sakura.Framework.Maths;

public partial struct Vector4 : System.IEquatable<Vector4>
{
    /// <summary>Creates a   new <see cref="T:System.Numerics.Vector4" /> object from the specified <see cref="T:System.Numerics.Vector2" /> object and a Z and a W component.</summary>
    /// <param name="value">The vector to use for the X and Y components.</param>
    /// <param name="z">The Z component.</param>
    /// <param name="w">The W component.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector4(Vector2 value, float z, float w)
    {
        this.Value = new System.Numerics.Vector4(value, z, w);
    }

    /// <summary>Constructs a new <see cref="T:System.Numerics.Vector4" /> object from the specified <see cref="T:System.Numerics.Vector3" /> object and a W component.</summary>
    /// <param name="value">The vector to use for the X, Y, and Z components.</param>
    /// <param name="w">The W component.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector4(Vector3 value, float w)
    {
        this.Value = new System.Numerics.Vector4(value, w);
    }

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector4" /> object whose four elements have the same value.</summary>
    /// <param name="value">The value to assign to all four elements.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector4(float value)
    {
        this.Value = new System.Numerics.Vector4(value);
    }

    /// <summary>Creates a vector whose elements have the specified values.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector4.X" /> field.</param>
    /// <param name="y">The value to assign to the <see cref="F:System.Numerics.Vector4.Y" /> field.</param>
    /// <param name="z">The value to assign to the <see cref="F:System.Numerics.Vector4.Z" /> field.</param>
    /// <param name="w">The value to assign to the <see cref="F:System.Numerics.Vector4.W" /> field.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector4(float x, float y, float z, float w)
    {
        this.Value = new System.Numerics.Vector4(x, y, z, w);
    }

    /// <summary>Constructs a vector from the given <see cref="T:System.ReadOnlySpan`1" />. The span must contain at least 4 elements.</summary>
    /// <param name="values">The span of elements to assign to the vector.</param>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Vector4(System.ReadOnlySpan<float> values)
    {
        this.Value = new System.Numerics.Vector4(values);
    }

    /// <summary>Adds two vectors together.</summary>
    /// <param name="left">The first vector to add.</param>
    /// <param name="right">The second vector to add.</param>
    /// <returns>The summed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator +(Vector4 left, Vector4 right) => left.Value + right.Value;

    /// <summary>Divides the first vector by the second.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector that results from dividing <paramref name="left" /> by <paramref name="right" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator /(Vector4 left, Vector4 right) => left.Value / right.Value;

    /// <summary>Divides the specified vector by a specified scalar value.</summary>
    /// <param name="value1">The vector.</param>
    /// <param name="value2">The scalar value.</param>
    /// <returns>The result of the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator /(Vector4 value1, float value2) => value1.Value / value2;

    /// <summary>Returns a value that indicates whether each pair of elements in two specified vectors is equal.</summary>
    /// <param name="left">The first vector to compare.</param>
    /// <param name="right">The second vector to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="left" /> and <paramref name="right" /> are equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Vector4 left, Vector4 right) => left.Value == right.Value;

    /// <summary>Returns a value that indicates whether two specified vectors are not equal.</summary>
    /// <param name="left">The first vector to compare.</param>
    /// <param name="right">The second vector to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="left" /> and <paramref name="right" /> are not equal; otherwise, <see langword="false" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Vector4 left, Vector4 right) => left.Value != right.Value;

    /// <summary>Returns a new vector whose values are the product of each pair of elements in two specified vectors.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The element-wise product vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator *(Vector4 left, Vector4 right) => left.Value * right.Value;

    /// <summary>Multiples the specified vector by the specified scalar value.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator *(Vector4 left, float right) => left.Value * right;

    /// <summary>Multiples the scalar value by the specified vector.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator *(float left, Vector4 right) => left * right.Value;

    /// <summary>Subtracts the second vector from the first.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector that results from subtracting <paramref name="right" /> from <paramref name="left" />.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator -(Vector4 left, Vector4 right) => left.Value - right.Value;

    /// <summary>Negates the specified vector.</summary>
    /// <param name="value">The vector to negate.</param>
    /// <returns>The negated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 operator -(Vector4 value) => -value.Value;

    /// <summary>Returns a vector whose elements are the absolute values of each of the specified vector's elements.</summary>
    /// <param name="value">A vector.</param>
    /// <returns>The absolute value vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Abs(Vector4 value) => System.Numerics.Vector4.Abs(value);

    /// <summary>Adds two vectors together.</summary>
    /// <param name="left">The first vector to add.</param>
    /// <param name="right">The second vector to add.</param>
    /// <returns>The summed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Add(Vector4 left, Vector4 right) => System.Numerics.Vector4.Add(left, right);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool All(Vector4 vector, float value) => System.Numerics.Vector4.All(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool AllWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.AllWhereAllBitsSet(vector);

    /// <summary>Computes the bitwise-and of a given vector and the ones complement of another vector.</summary>
    /// <param name="left">The vector to bitwise-and with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to that is ones-complemented before being bitwise-and with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns>The bitwise-and of <code data-dev-comment-type="paramref">left</code> and the ones-complement of <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 AndNot(Vector4 left, Vector4 right) => System.Numerics.Vector4.AndNot(left, right);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool Any(Vector4 vector, float value) => System.Numerics.Vector4.Any(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool AnyWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.AnyWhereAllBitsSet(vector);

    /// <summary>Computes the bitwise-and of two vectors.</summary>
    /// <param name="left">The vector to bitwise-and with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to bitwise-and with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns>The bitwise-and of <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 BitwiseAnd(Vector4 left, Vector4 right) => System.Numerics.Vector4.BitwiseAnd(left, right);

    /// <summary>Computes the bitwise-or of two vectors.</summary>
    /// <param name="left">The vector to bitwise-or with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to bitwise-or with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns>The bitwise-or of <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 BitwiseOr(Vector4 left, Vector4 right) => System.Numerics.Vector4.BitwiseOr(left, right);

    /// <summary>Restricts a vector between a minimum and a maximum value.</summary>
    /// <param name="value1">The vector to restrict.</param>
    /// <param name="min">The minimum value.</param>
    /// <param name="max">The maximum value.</param>
    /// <returns>The restricted vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Clamp(Vector4 value1, Vector4 min, Vector4 max) => System.Numerics.Vector4.Clamp(value1, min, max);

    /// <summary>Restricts a vector between a minimum and a maximum value using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>..</summary>
    /// <param name="value1" />
    /// <param name="min">The minimum value.</param>
    /// <param name="max">The maximum value.</param>
    /// <returns>The restricted vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 ClampNative(Vector4 value1, Vector4 min, Vector4 max) => System.Numerics.Vector4.ClampNative(value1, min, max);

    /// <summary>Conditionally selects a value from two vectors on a bitwise basis.</summary>
    /// <param name="condition">The mask that is used to select a value from <code data-dev-comment-type="paramref">left</code> or <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="left">The vector that is selected when the corresponding bit in <code data-dev-comment-type="paramref">condition</code> is one.</param>
    /// <param name="right">The vector that is selected when the corresponding bit in <code data-dev-comment-type="paramref">condition</code> is zero.</param>
    /// <returns>A vector whose bits come from <code data-dev-comment-type="paramref">left</code> or <code data-dev-comment-type="paramref">right</code> based on the value of <code data-dev-comment-type="paramref">condition</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 ConditionalSelect(Vector4 condition, Vector4 left, Vector4 right) => System.Numerics.Vector4.ConditionalSelect(condition, left, right);

    /// <summary>Copies the per-element sign of a vector to the per-element sign of another vector.</summary>
    /// <param name="value">The vector whose magnitude is used in the result.</param>
    /// <param name="sign">The vector whose sign is used in the result.</param>
    /// <returns>A vector with the magnitude of <code data-dev-comment-type="paramref">value</code> and the sign of <code data-dev-comment-type="paramref">sign</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 CopySign(Vector4 value, Vector4 sign) => System.Numerics.Vector4.CopySign(value, sign);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Count(Vector4 vector, float value) => System.Numerics.Vector4.Count(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int CountWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.CountWhereAllBitsSet(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Cos(Vector4 vector) => System.Numerics.Vector4.Cos(vector);

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector4" /> object whose four elements have the same value.</summary>
    /// <param name="value">The value to assign to all four elements.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector4" /> whose four elements have the same value.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Create(float value) => System.Numerics.Vector4.Create(value);

    /// <summary>Creates a new <see cref="T:System.Numerics.Vector4" /> object from the specified <see cref="T:System.Numerics.Vector2" /> object and a Z and a W component.</summary>
    /// <param name="vector">The vector to use for the X and Y components.</param>
    /// <param name="z">The Z component.</param>
    /// <param name="w">The W component.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector4" /> from the specified <see cref="T:System.Numerics.Vector2" /> object and a Z and a W component.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Create(Vector2 vector, float z, float w) => System.Numerics.Vector4.Create(vector, z, w);

    /// <summary>Constructs a new <see cref="T:System.Numerics.Vector4" /> object from the specified <see cref="T:System.Numerics.Vector3" /> object and a W component.</summary>
    /// <param name="vector">The vector to use for the X, Y, and Z components.</param>
    /// <param name="w">The W component.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector4" /> from the specified <see cref="T:System.Numerics.Vector3" /> object and a W component.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Create(Vector3 vector, float w) => System.Numerics.Vector4.Create(vector, w);

    /// <summary>Creates a vector whose elements have the specified values.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector4.X" /> field.</param>
    /// <param name="y">The value to assign to the <see cref="F:System.Numerics.Vector4.Y" /> field.</param>
    /// <param name="z">The value to assign to the <see cref="F:System.Numerics.Vector4.Z" /> field.</param>
    /// <param name="w">The value to assign to the <see cref="F:System.Numerics.Vector4.W" /> field.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector4" /> whose elements have the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Create(float x, float y, float z, float w) => System.Numerics.Vector4.Create(x, y, z, w);

    /// <summary>Constructs a vector from the given <see cref="T:System.ReadOnlySpan`1" />. The span must contain at least 4 elements.</summary>
    /// <param name="values">The span of elements to assign to the vector.</param>
    /// <returns>A new <see cref="T:System.Numerics.Vector4" /> whose elements have the specified values.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Create(System.ReadOnlySpan<float> values) => System.Numerics.Vector4.Create(values);

    /// <summary>Creates a vector with <see cref="F:System.Numerics.Vector4.X" /> initialized to the specified value and the remaining elements initialized to zero.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector4.X" /> field.</param>
    /// <returns>A <see cref="T:System.Numerics.Vector4" /> with <see cref="F:System.Numerics.Vector4.X" /> initialized <paramref name="x" /> and the remaining elements initialized to zero.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 CreateScalar(float x) => System.Numerics.Vector4.CreateScalar(x);

    /// <summary>Creates a vector with <see cref="F:System.Numerics.Vector4.X" /> initialized to the specified value and the remaining elements left uninitialized.</summary>
    /// <param name="x">The value to assign to the <see cref="F:System.Numerics.Vector4.X" /> field.</param>
    /// <returns>A <see cref="T:System.Numerics.Vector4" /> with <see cref="F:System.Numerics.Vector4.X" /> initialized <paramref name="x" /> and the remaining elements left uninitialized.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 CreateScalarUnsafe(float x) => System.Numerics.Vector4.CreateScalarUnsafe(x);

    /// <param name="degrees" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 DegreesToRadians(Vector4 degrees) => System.Numerics.Vector4.DegreesToRadians(degrees);

    /// <summary>Computes the Euclidean distance between the two given points.</summary>
    /// <param name="value1">The first point.</param>
    /// <param name="value2">The second point.</param>
    /// <returns>The distance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Distance(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.Distance(value1, value2);

    /// <summary>Returns the Euclidean distance squared between two specified points.</summary>
    /// <param name="value1">The first point.</param>
    /// <param name="value2">The second point.</param>
    /// <returns>The distance squared.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float DistanceSquared(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.DistanceSquared(value1, value2);

    /// <summary>Divides the first vector by the second.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The vector resulting from the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Divide(Vector4 left, Vector4 right) => System.Numerics.Vector4.Divide(left, right);

    /// <summary>Divides the specified vector by a specified scalar value.</summary>
    /// <param name="left">The vector.</param>
    /// <param name="divisor">The scalar value.</param>
    /// <returns>The vector that results from the division.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Divide(Vector4 left, float divisor) => System.Numerics.Vector4.Divide(left, divisor);

    /// <summary>Returns the dot product of two vectors.</summary>
    /// <param name="vector1">The first vector.</param>
    /// <param name="vector2">The second vector.</param>
    /// <returns>The dot product.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Dot(Vector4 vector1, Vector4 vector2) => System.Numerics.Vector4.Dot(vector1, vector2);

    /// <summary><para>Computes the cross product of two vectors. For homogeneous coordinates, the product of the weights is the new weight for the resulting product.</para></summary>
    /// <param name="vector1">The first vector.</param>
    /// <param name="vector2">The second vector.</param>
    /// <returns>The cross product.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Cross(Vector4 vector1, Vector4 vector2) => System.Numerics.Vector4.Cross(vector1, vector2);

    /// <summary>Compares two vectors to determine if they are equal on a per-element basis.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code> were equal.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Equals(Vector4 left, Vector4 right) => System.Numerics.Vector4.Equals(left, right);

    /// <summary>Compares two vectors to determine if all elements are equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if all elements in <code data-dev-comment-type="paramref">left</code> were equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool EqualsAll(Vector4 left, Vector4 right) => System.Numerics.Vector4.EqualsAll(left, right);

    /// <summary>Compares two vectors to determine if any elements are equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if any elements in <code data-dev-comment-type="paramref">left</code> was equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool EqualsAny(Vector4 left, Vector4 right) => System.Numerics.Vector4.EqualsAny(left, right);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Exp(Vector4 vector) => System.Numerics.Vector4.Exp(vector);

    /// <param name="left" />
    /// <param name="right" />
    /// <param name="addend" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 FusedMultiplyAdd(Vector4 left, Vector4 right, Vector4 addend) => System.Numerics.Vector4.FusedMultiplyAdd(left, right, addend);

    /// <summary>Compares two vectors to determine which is greater on a per-element basis.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code> were greater.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 GreaterThan(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThan(left, right);

    /// <summary>Compares two vectors to determine if all elements are greater.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if all elements in <code data-dev-comment-type="paramref">left</code> were greater than the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanAll(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThanAll(left, right);

    /// <summary>Compares two vectors to determine if any elements are greater.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if any elements in <code data-dev-comment-type="paramref">left</code> was greater than the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanAny(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThanAny(left, right);

    /// <summary>Compares two vectors to determine which is greater or equal on a per-element basis.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code> were greater or equal.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 GreaterThanOrEqual(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThanOrEqual(left, right);

    /// <summary>Compares two vectors to determine if all elements are greater or equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if all elements in <code data-dev-comment-type="paramref">left</code> were greater than or equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanOrEqualAll(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThanOrEqualAll(left, right);

    /// <summary>Compares two vectors to determine if any elements are greater or equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if any elements in <code data-dev-comment-type="paramref">left</code> was greater than or equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool GreaterThanOrEqualAny(Vector4 left, Vector4 right) => System.Numerics.Vector4.GreaterThanOrEqualAny(left, right);

    /// <param name="x" />
    /// <param name="y" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Hypot(Vector4 x, Vector4 y) => System.Numerics.Vector4.Hypot(x, y);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IndexOf(Vector4 vector, float value) => System.Numerics.Vector4.IndexOf(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IndexOfWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.IndexOfWhereAllBitsSet(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsEvenInteger(Vector4 vector) => System.Numerics.Vector4.IsEvenInteger(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsFinite(Vector4 vector) => System.Numerics.Vector4.IsFinite(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsInfinity(Vector4 vector) => System.Numerics.Vector4.IsInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsInteger(Vector4 vector) => System.Numerics.Vector4.IsInteger(vector);

    /// <summary>Determines which elements in a vector are NaN.</summary>
    /// <param name="vector">The vector to be checked.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">vector</code> were NaN.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsNaN(Vector4 vector) => System.Numerics.Vector4.IsNaN(vector);

    /// <summary>Determines which elements in a vector represents negative real numbers.</summary>
    /// <param name="vector">The vector to be checked.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">vector</code> were negative.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsNegative(Vector4 vector) => System.Numerics.Vector4.IsNegative(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsNegativeInfinity(Vector4 vector) => System.Numerics.Vector4.IsNegativeInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsNormal(Vector4 vector) => System.Numerics.Vector4.IsNormal(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsOddInteger(Vector4 vector) => System.Numerics.Vector4.IsOddInteger(vector);

    /// <summary>Determines which elements in a vector represents positive real numbers.</summary>
    /// <param name="vector">The vector to be checked.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">vector</code> were positive.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsPositive(Vector4 vector) => System.Numerics.Vector4.IsPositive(vector);

    /// <summary>Determines which elements in a vector are positive infinity.</summary>
    /// <param name="vector">The vector to be checked.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">vector</code> were positive infinity.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsPositiveInfinity(Vector4 vector) => System.Numerics.Vector4.IsPositiveInfinity(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsSubnormal(Vector4 vector) => System.Numerics.Vector4.IsSubnormal(vector);

    /// <summary>Determines which elements in a vector are zero.</summary>
    /// <param name="vector">The vector to be checked.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if the corresponding elements in <code data-dev-comment-type="paramref">vector</code> were zero.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 IsZero(Vector4 vector) => System.Numerics.Vector4.IsZero(vector);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int LastIndexOf(Vector4 vector, float value) => System.Numerics.Vector4.LastIndexOf(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int LastIndexOfWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.LastIndexOfWhereAllBitsSet(vector);

    /// <summary>Performs a linear interpolation between two vectors based on the given weighting.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <param name="amount">A value between 0 and 1 that indicates the weight of <code data-dev-comment-type="paramref">value2</code>.</param>
    /// <returns>The interpolated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Lerp(Vector4 value1, Vector4 value2, float amount) => System.Numerics.Vector4.Lerp(value1, value2, amount);

    /// <param name="value1" />
    /// <param name="value2" />
    /// <param name="amount" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Lerp(Vector4 value1, Vector4 value2, Vector4 amount) => System.Numerics.Vector4.Lerp(value1, value2, amount);

    /// <summary>Compares two vectors to determine which is less on a per-element basis.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code> were less.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 LessThan(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThan(left, right);

    /// <summary>Compares two vectors to determine if all elements are less.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if all elements in <code data-dev-comment-type="paramref">left</code> were less than the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanAll(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThanAll(left, right);

    /// <summary>Compares two vectors to determine if any elements are less.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if any elements in <code data-dev-comment-type="paramref">left</code> was less than the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanAny(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThanAny(left, right);

    /// <summary>Compares two vectors to determine which is less or equal on a per-element basis.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <returns>A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code> were less or equal.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 LessThanOrEqual(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThanOrEqual(left, right);

    /// <summary>Compares two vectors to determine if all elements are less or equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if all elements in <code data-dev-comment-type="paramref">left</code> were less than or equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanOrEqualAll(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThanOrEqualAll(left, right);

    /// <summary>Compares two vectors to determine if any elements are less or equal.</summary>
    /// <param name="left">The vector to compare with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to compare with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns><code data-dev-comment-type="langword">true</code> if any elements in <code data-dev-comment-type="paramref">left</code> was less than or equal to the corresponding element in <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool LessThanOrEqualAny(Vector4 left, Vector4 right) => System.Numerics.Vector4.LessThanOrEqualAny(left, right);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Log(Vector4 vector) => System.Numerics.Vector4.Log(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Log2(Vector4 vector) => System.Numerics.Vector4.Log2(vector);

    /// <summary>Loads a vector from the given source.</summary>
    /// <param name="source">The source from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector4 Load(float* source) => System.Numerics.Vector4.Load(source);

    /// <summary>Loads a vector from the given aligned source.</summary>
    /// <param name="source">The aligned source from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector4 LoadAligned(float* source) => System.Numerics.Vector4.LoadAligned(source);

    /// <summary>Loads a vector from the given aligned source.</summary>
    /// <param name="source">The aligned source from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static unsafe Vector4 LoadAlignedNonTemporal(float* source) => System.Numerics.Vector4.LoadAlignedNonTemporal(source);

    /// <summary>Loads a vector from the given source.</summary>
    /// <param name="source">The source from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 LoadUnsafe(float source) => System.Numerics.Vector4.LoadUnsafe(source);

    /// <summary>Loads a vector from the given source and element offset.</summary>
    /// <param name="source">The source to which <code data-dev-comment-type="paramref">elementOffset</code> will be added before loading the vector.</param>
    /// <param name="elementOffset">The element offset from <code data-dev-comment-type="paramref">source</code> from which the vector will be loaded.</param>
    /// <returns>The vector loaded from <code data-dev-comment-type="paramref">source</code> plus <code data-dev-comment-type="paramref">elementOffset</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 LoadUnsafe(float source, nuint elementOffset) => System.Numerics.Vector4.LoadUnsafe(source, elementOffset);

    /// <summary>Returns a vector whose elements are the maximum of each of the pairs of elements in two specified vectors.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <returns>The maximized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Max(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.Max(value1, value2);

    /// <summary>Compares two vectors to compute which has the greater magnitude on a per-element basis.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a greater magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MaxMagnitude(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MaxMagnitude(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which has the greater magnitude and returning the other value if an input is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a greater magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MaxMagnitudeNumber(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MaxMagnitudeNumber(value1, value2);

    /// <summary>Compare two vectors to determine which is greater on a per-element basis using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is greater than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MaxNative(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MaxNative(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which is greater and returning the other value if an element is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is greater than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MaxNumber(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MaxNumber(value1, value2);

    /// <summary>Returns a vector whose elements are the minimum of each of the pairs of elements in two specified vectors.</summary>
    /// <param name="value1">The first vector.</param>
    /// <param name="value2">The second vector.</param>
    /// <returns>The minimized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Min(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.Min(value1, value2);

    /// <summary>Compares two vectors to compute which has the lesser magnitude on a per-element basis.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a lesser magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MinMagnitude(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MinMagnitude(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which has the lesser magnitude and returning the other value if an input is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it has a lesser magnitude than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MinMagnitudeNumber(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MinMagnitudeNumber(value1, value2);

    /// <summary>Compare two vectors to determine which is lesser on a per-element basis using platform specific behavior for <code data-dev-comment-type="c">NaN</code> and <code data-dev-comment-type="c">NegativeZero</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is lesser than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MinNative(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MinNative(value1, value2);

    /// <summary>Compares two vectors, on a per-element basis, to compute which is lesser and returning the other value if an element is <code data-dev-comment-type="c">NaN</code>.</summary>
    /// <param name="value1" />
    /// <param name="value2" />
    /// <returns>A vector where the corresponding element comes from <code data-dev-comment-type="paramref">left</code> if it is lesser than <code data-dev-comment-type="paramref">right</code>; otherwise, <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MinNumber(Vector4 value1, Vector4 value2) => System.Numerics.Vector4.MinNumber(value1, value2);

    /// <summary>Returns a new vector whose values are the product of each pair of elements in two specified vectors.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The element-wise product vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Multiply(Vector4 left, Vector4 right) => System.Numerics.Vector4.Multiply(left, right);

    /// <summary>Multiplies a vector by a specified scalar.</summary>
    /// <param name="left">The vector to multiply.</param>
    /// <param name="right">The scalar value.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Multiply(Vector4 left, float right) => System.Numerics.Vector4.Multiply(left, right);

    /// <summary>Multiplies a scalar value by a specified vector.</summary>
    /// <param name="left">The scaled value.</param>
    /// <param name="right">The vector.</param>
    /// <returns>The scaled vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Multiply(float left, Vector4 right) => System.Numerics.Vector4.Multiply(left, right);

    /// <param name="left" />
    /// <param name="right" />
    /// <param name="addend" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 MultiplyAddEstimate(Vector4 left, Vector4 right, Vector4 addend) => System.Numerics.Vector4.MultiplyAddEstimate(left, right, addend);

    /// <summary>Negates a specified vector.</summary>
    /// <param name="value">The vector to negate.</param>
    /// <returns>The negated vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Negate(Vector4 value) => System.Numerics.Vector4.Negate(value);

    /// <param name="vector" />
    /// <param name="value" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool None(Vector4 vector, float value) => System.Numerics.Vector4.None(vector, value);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool NoneWhereAllBitsSet(Vector4 vector) => System.Numerics.Vector4.NoneWhereAllBitsSet(vector);

    /// <summary>Returns a vector with the same direction as the specified vector, but with a length of one.</summary>
    /// <param name="vector">The vector to normalize.</param>
    /// <returns>The normalized vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Normalize(Vector4 vector) => System.Numerics.Vector4.Normalize(vector);

    /// <summary>Computes the ones-complement of a vector.</summary>
    /// <param name="value" />
    /// <returns>A vector whose elements are the ones-complement of the corresponding elements in <code data-dev-comment-type="paramref">vector</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 OnesComplement(Vector4 value) => System.Numerics.Vector4.OnesComplement(value);

    /// <param name="radians" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 RadiansToDegrees(Vector4 radians) => System.Numerics.Vector4.RadiansToDegrees(radians);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Round(Vector4 vector) => System.Numerics.Vector4.Round(vector);

    /// <param name="vector" />
    /// <param name="mode" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Round(Vector4 vector, System.MidpointRounding mode) => System.Numerics.Vector4.Round(vector, mode);

    /// <summary>Creates a new vector by selecting values from an input vector using a set of indices.</summary>
    /// <param name="vector">The input vector from which values are selected.</param>
    /// <param name="xIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector4.X" /> in the result.</param>
    /// <param name="yIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector4.Y" /> in the result</param>
    /// <param name="zIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector4.Z" /> in the result</param>
    /// <param name="wIndex">The index used to select a value from <paramref name="vector" /> to be used as the value of <see cref="F:System.Numerics.Vector4.W" /> in the result</param>
    /// <returns>A new vector containing the values from <paramref name="vector" /> selected by the given indices.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Shuffle(Vector4 vector, byte xIndex, byte yIndex, byte zIndex, byte wIndex) => System.Numerics.Vector4.Shuffle(vector, xIndex, yIndex, zIndex, wIndex);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Sin(Vector4 vector) => System.Numerics.Vector4.Sin(vector);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static (System.Numerics.Vector4 Sin, System.Numerics.Vector4 Cos) SinCos(Vector4 vector) => System.Numerics.Vector4.SinCos(vector);

    /// <summary>Returns a vector whose elements are the square root of each of a specified vector's elements.</summary>
    /// <param name="value">A vector.</param>
    /// <returns>The square root vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 SquareRoot(Vector4 value) => System.Numerics.Vector4.SquareRoot(value);

    /// <summary>Subtracts the second vector from the first.</summary>
    /// <param name="left">The first vector.</param>
    /// <param name="right">The second vector.</param>
    /// <returns>The difference vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Subtract(Vector4 left, Vector4 right) => System.Numerics.Vector4.Subtract(left, right);

    /// <summary>Computes the sum of all elements in a vector.</summary>
    /// <param name="value" />
    /// <returns>The sum of all elements in <code data-dev-comment-type="paramref">vector</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float Sum(Vector4 value) => System.Numerics.Vector4.Sum(value);

    /// <summary>Transforms a two-dimensional vector by a specified 4x4 matrix.</summary>
    /// <param name="position">The vector to transform.</param>
    /// <param name="matrix">The transformation matrix.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector2 position, Matrix4x4 matrix) => System.Numerics.Vector4.Transform(position, matrix);

    /// <summary>Transforms a two-dimensional vector by the specified Quaternion rotation value.</summary>
    /// <param name="value">The vector to rotate.</param>
    /// <param name="rotation">The rotation to apply.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector2 value, System.Numerics.Quaternion rotation) => System.Numerics.Vector4.Transform(value, rotation);

    /// <summary>Transforms a three-dimensional vector by a specified 4x4 matrix.</summary>
    /// <param name="position">The vector to transform.</param>
    /// <param name="matrix">The transformation matrix.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector3 position, Matrix4x4 matrix) => System.Numerics.Vector4.Transform(position, matrix);

    /// <summary>Transforms a three-dimensional vector by the specified Quaternion rotation value.</summary>
    /// <param name="value">The vector to rotate.</param>
    /// <param name="rotation">The rotation to apply.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector3 value, System.Numerics.Quaternion rotation) => System.Numerics.Vector4.Transform(value, rotation);

    /// <summary>Transforms a four-dimensional vector by a specified 4x4 matrix.</summary>
    /// <param name="vector">The vector to transform.</param>
    /// <param name="matrix">The transformation matrix.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector4 vector, Matrix4x4 matrix) => System.Numerics.Vector4.Transform(vector, matrix);

    /// <summary>Transforms a four-dimensional vector by the specified Quaternion rotation value.</summary>
    /// <param name="value">The vector to rotate.</param>
    /// <param name="rotation">The rotation to apply.</param>
    /// <returns>The transformed vector.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Transform(Vector4 value, System.Numerics.Quaternion rotation) => System.Numerics.Vector4.Transform(value, rotation);

    /// <param name="vector" />
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Truncate(Vector4 vector) => System.Numerics.Vector4.Truncate(vector);

    /// <summary>Computes the exclusive-or of two vectors.</summary>
    /// <param name="left">The vector to exclusive-or with <code data-dev-comment-type="paramref">right</code>.</param>
    /// <param name="right">The vector to exclusive-or with <code data-dev-comment-type="paramref">left</code>.</param>
    /// <returns>The exclusive-or of <code data-dev-comment-type="paramref">left</code> and <code data-dev-comment-type="paramref">right</code>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Vector4 Xor(Vector4 left, Vector4 right) => System.Numerics.Vector4.Xor(left, right);

    /// <summary>Returns the length of this vector object.</summary>
    /// <returns>The vector's length.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float Length() => this.Value.Length();

    /// <summary>Returns the length of the vector squared.</summary>
    /// <returns>The vector's length squared.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float LengthSquared() => this.Value.LengthSquared();

    /// <summary>Returns the string representation of the current instance using default formatting.</summary>
    /// <returns>The string representation of the current instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override string ToString() => this.Value.ToString();

    /// <summary>Indicates whether the current object is equal to another object of the same type.</summary>
    /// <param name="other">An object to compare with this object.</param>
    /// <returns><c>true</c> if the current object is equal to the <paramref name="other" /> parameter; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Vector4 other) => this.Value.Equals(other.Value);

    /// <summary>Indicates whether this instance and a specified object are equal.</summary>
    /// <param name="obj">The object to compare with the current instance.</param>
    /// <returns><c>true</c> if <paramref name="obj" /> and this instance are the same type and represent the same value; otherwise, <c>false</c>.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object obj) => obj is Vector4 other && Equals(other);

    /// <summary>Returns the hash code for this instance.</summary>
    /// <returns>A 32-bit signed integer that is the hash code for this instance.</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode() => this.Value.GetHashCode();
}
